### ISSUE TITLE
Непонятно

### ISSUE THREAD

**Issue by SemgaGOD** [reepov/Petrenko-Goltzman-Indexes-Comparing#1]
Ты мне объясни, что это ебатория то

**Comment by reepov** [comment]
Индекс Петренко для первой буквы в строке равен 0,5, для каждой последующей – на единицу больше. Индекс Петренко для строки равен сумме индексов составляющих её букв, дополнительно умноженной на длину строки. Все разделительные символы, включая знаки препинания, дефисы, апострофы и пробелы, при расчёте индекса не учитываются. Например, для предложения «Не выходи из комнаты, не совершай ошибку.» индекс Петренко равен 17968,5.
Имеется набор строк на русском языке и набор строк на английском языке, при этом каждая из последних дополнительно снабжена комментарием не короче одного и не длиннее пяти слов. Комментарий идёт после основной строки и отделяется от неё символом «|».
Для каждой русской строки необходимо найти все английские строки такие, что индекс Петренко для русской строки равен сумме индекса Петренко для английской строки (без учёта комментария) и индекса комментария.

**Comment by reepov** [comment]
> Ты мне объясни, что это ебатория то

Напишите программу на языке C#, сопоставляющую строки по методу Петренко – Гольцмана.

**Comment by SemgaGOD** [comment]
Ничего не понял, но ладно. Спокойной ночи
